version: '3.8'

services:
  flowbite-mcp:
    build: .
    container_name: flowbite-mcp-server
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - DEBUG=0
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000" # Optional: if running HTTP server
    healthcheck:
      test: [ "CMD", "python", "-c", "import src.server; print('OK')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp-data:
    driver: local
